### ISSUE TITLE
Cannot index file inside subfolder in site folder

### ISSUE THREAD

**Issue by multidecay** [multidecay/soupault-digital-garden#1]
Recently, I meet a bug that show subdirectory is not indexed but when index dumped into json it indexed. 

To reproduce:
 - Create any subfolder with any .md file inside it.
 - Add `print(site_index)` at end of  `plugins/populate-seed-index.lua`.
 - Open `soupault.toml`, go to section `index` then add `dump_json=index.json` in it.
 - Run `make build` then compare the build message that shown json and `index.json` json.

Suspect: Index views to early executed by indexer and not index the latter page that indexed. Only indexed in `site` folder, when read subdirs.

Solution: Solved! each subfolder treated as sections, so if you want to index subfolder you need specified it in `index.views`.

```toml
[index.views.main-index]
  section = ["","yoursubdir"] # this option if you didn't understand regex
  path_regex = "/*" # regex
```

It, support regex using `path_regex = "/*"`, to auto read all subdir.

Ref:
- [Soupault limiting options](https://soupault.app/reference-manual/#glossary)
